model_list:
  - model_name: gpt-4
    litellm_params:
      model: gpt-4-1106-preview
      api_version: "2023-05-15"
- model_name: openrouter/google/palm-2-chat-bison
    litellm_params:
      model: openrouter/google/palm-2-chat-bison
      rpm: 100

litellm_settings:
  drop_params: True
  set_verbose: True

general_settings: 
  # master_key: sk-1234 # [OPTIONAL] Only use this if you to require all calls to contain this key (Authorization: Bearer sk-1234)
  # database_url: "postgresql://<user>:<password>@<host>:<port>/<dbname>" # [OPTIONAL] use for token-based auth to proxy

environment_variables:
  # settings for using redis caching
  # REDIS_HOST: redis-16337.c322.us-east-1-2.ec2.cloud.redislabs.com
  # REDIS_PORT: "16337"
  # REDIS_PASSWORD: 
